name: Deploy Dev Branch

on:
  push:
    branches:
      - dev_thien_refactor-clean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build & Push Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: daithien/socialbook-be:dev

      # 4️⃣ Build & Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: daithien/socialbook-fe:dev

      # 5️⃣ Deploy to Droplet
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            script: |
              cd ~/socialbook
            
              echo "Pull latest images..."
              docker compose pull
            
              echo "Restart containers..."
              docker compose up -d --remove-orphans
            
              echo "Deploy completed!"
